import { thing } from './imports';

export const routes = [
  { path: '/', element: <thing.Home /> },
  { path: '/cart', element: <thing.Cart /> },
  { path: '/about_us', element: <thing.AboutUs /> },
  { path: '/contact', element: <thing.Contact /> },

  { path: '/aircraftcarrier', element: <thing.AircraftCarrier /> },
  { path: '/airplane', element: <thing.Airplane /> },
  { path: '/ak47', element: <thing.AK47 /> },
  { path: '/battleship', element: <thing.Battleship /> },
  { path: '/bomber', element: <thing.Bomber /> },
  { path: '/buggy', element: <thing.Buggy /> },
  { path: '/bullet', element: <thing.Bullet /> },
  { path: '/cadillac', element: <thing.Cadillac /> },
  { path: '/cruiseship', element: <thing.CruiseShip /> },
  { path: '/defender', element: <thing.Defender /> },
  { path: '/dragger', element: <thing.Dragger /> },
  { path: '/f1', element: <thing.F1 /> },
  { path: '/fighter', element: <thing.Fighter /> },
  { path: '/flamethrower', element: <thing.Flamethrower /> },
  { path: '/fortuner', element: <thing.Fortuner /> },
  { path: '/fortunerlegender', element: <thing.FortunerLegender /> },
  { path: '/granade', element: <thing.Granade /> },
  { path: '/granadelauncher', element: <thing.GranadeLauncher /> },
  { path: '/helicopter', element: <thing.Helicopter /> },
  { path: '/hk416', element: <thing.HK416 /> },
  { path: '/jeep', element: <thing.Jeep /> },
  { path: '/kasti', element: <thing.Kasti /> },
  { path: '/katana', element: <thing.Katana /> },
  { path: '/katta', element: <thing.Katta /> },
  { path: '/landmine', element: <thing.Landmine /> },
  { path: '/machinegun', element: <thing.MachineGun /> },
  { path: '/missile', element: <thing.Missile /> },
  { path: '/mortar', element: <thing.Mortar /> },
  { path: '/mp40', element: <thing.MP40 /> },
  { path: '/nuke', element: <thing.Nuke /> },
  { path: '/pistol', element: <thing.Pistol /> },
  { path: '/rangerover', element: <thing.RangeRover /> },
  { path: '/rocket', element: <thing.Rocket /> },
  { path: '/rpg', element: <thing.RPG /> },
  { path: '/s400', element: <thing.S400 /> },
  { path: '/safari', element: <thing.Safari /> },
  { path: '/scorpion', element: <thing.Scorpion /> },
  { path: '/shotgun', element: <thing.Shotgun /> },
  { path: '/sniper', element: <thing.Sniper /> },
  { path: '/submarine', element: <thing.Submarine /> },
  { path: '/tank', element: <thing.Tank /> },
  { path: '/tankmine', element: <thing.TankMine /> },
  { path: '/thar', element: <thing.Thar /> },
  { path: '/tharroxx', element: <thing.TharRoxx /> },
  { path: '/tractor', element: <thing.Tractor /> },
  { path: '/truck', element: <thing.Truck /> },
  { path: '/yacht', element: <thing.Yacht /> },
  { path: '/xuv700', element: <thing.XUV700 /> },
];
